### ISSUE TITLE
Fontx: not found.

### ISSUE THREAD

**Issue by hyhkjiy** [nopnop2002/esp-idf-st7789#4]
Like this:
![image](https://user-images.githubusercontent.com/18144117/61201486-3e21ce00-a717-11e9-949a-1ed90fde1921.png)
How should I put the font file into SPIFFS Filesystem?

**Comment by nopnop2002** [comment]
Thanks for reporting this.
It's a bug in Makefile.
I was fixed it.

**Comment by hyhkjiy** [comment]
Thanks for the quick response!
I ran make clean and rebuilt it, but I still have the same error as before.
Do you need to install dependencies, such as "spiffs_create_partition_image"?
Or what options do I need to add when making a flash?

**Comment by hyhkjiy** [comment]
I solved this problem by upgrading the version of esp-idf.

**Comment by nopnop2002** [comment]
Yes.

ESP-IDF is updated frequently.
